name: ArcticGuilds
author: Kyro, wiji
version: 1.0.0
main: net.pitsim.arcticguilds.ArcticGuilds
description: Guild system
depend:
  - Vault
  - PlaceholderAPI
#  - ProtocolLib
  - Essentials
commands:
  guild:
    description: Main guild command
    aliases:
      - g
      - group
  gadmin:
    description: Guild admin command
    aliases:
      - ga